name: Test notes app
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_DIRECT_URL: ${{ secrets.DATABASE_DIRECT_URL }}
  PORT: ${{ vars.BACKEND_PORT }}
  TOKEN_KEY: ${{ vars.BACKEND_TOKEN_KEY }}
  MAILER_USER: ${{ vars.MAILER_USER }}
  MAILER_PASSWORD: ${{ secrets.MAILER_PASSWORD }}
  MAIL_NOREPLY: ${{ vars.MAIL_NOREPLY }}
  HOME_URL: http://localhost:5173

jobs:
  cypress-tests-run:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install backend
        working-directory: ./server
        run: npm ci
      - name: Deploy prisma changes
        working-directory: ./server
        run: npm run prisma:deploy
      - name: Start backend
        working-directory: ./server
        run: npm run start &
      - run: echo "Backend running"

      - name: Install Cypress on FrontEnd and run E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client
          build: npm ci
          start: npm run dev
          wait-on: 'http://127.0.0.1:5173'
          browser: chrome
        env:
          cypress_test_user: ${{ secrets.TEST_USER }}
          cypress_test_user_password: ${{ secrets.TEST_USER_PASSWORD }}
          cypress_test_user_name: ${{ secrets.USER_NAME }}

      - name: Upload error screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots
          path: client/cypress/screenshots

      - name: Login to Docker private repo
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        env:
          HOME_URL: http://localhost
          NODE_ENV: production
        with:
          push: true
          tags: notes-app/backend:latest
          context: ./server/
          file: ./server/Dockerfile
          
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        env:
          NODE_ENV: production
        with:
          push: true
          tags: notes-app/frontend:latest
          context: ./client/
          file: ./client/Dockerfile

      - run: echo "üçè This job's status is ${{ job.status }}."